"""add stripe_product_id to subscription_tiers

Revision ID: 0e87c6fb7865
Revises: c36e915eb324
Create Date: 2026-03-21 14:02:28.053207
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e87c6fb7865'
down_revision: Union[str, None] = 'c36e915eb324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
